env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:vue/vue3-recommended'
globals:
  defineProps: readonly
  defineEmits: readonly
  defineExpose: readonly
  withDefaults: readonly
parser: 'vue-eslint-parser'
parserOptions:
  ecmaVersion: 2020
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules:
  indent:
    - error
    - 2
  quotes:
    - error
    - single
  comma-dangle:
    - error
    - always-multiline
  max-len:
    - 2   # severity
    - 120 #code
    - 2   #tabWidth
  semi:
    - error
    - always
  array-bracket-spacing:
    - error
    - always
  object-curly-spacing:
    - error
    - always
  vue/multi-word-component-names: off
